#!/bin/sh

set -e

P=$(pwd)
RUBY_URL='http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.1.tar.gz'

apt-get install build-essential curl -qqy

cd /tmp
curl  $RUBY_URL | tar xzf - -C /tmp/ruby
cd /tmp/ruby
make
make install
cd $P
