#!/usr/bin/env bash

set -e
source config
[[ -d $WORK ]] || mkdir -p $WORK
[[ -e $WORK/.base_install ]] || ./base/install

echo "=== Running Ruby 2.0 Install ==="

RUBY_URL='http://cache.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p451.tar.gz'

apt-get install build-essential curl -qqy

BUILD_DIR=/tmp/ruby-2.0.0-p451
[[ -d $BUILD_DIR ]] || curl  $RUBY_URL | tar xzf - -C /tmp
pushd $BUILD_DIR
./configure
make
make install
popd

touch $WORK/.ruby-2.0_install
