#!/usr/bin/env bash

set -e

P=$(pwd)
RUBY_URL='http://cache.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p451.tar.gz'

apt-get install build-essential curl -qqy

BUILD_DIR=/tmp/ruby-2.0.0-p451
[[ -d $BUILD_DIR ]] || curl  $RUBY_URL | tar xzf - -C /tmp
pushd $BUILD_DIR
./configure
make
make install
popd
